### ISSUE TITLE
Refactor getNamedType constructs

### ISSUE THREAD

**Issue by erikgaal** [scrnhq/laravel-bakery#21]
This fragment of code 

```php
if (is_array($type)) {
    $type = Type::getNamedType($type['type']);
} else {
    $type = Type::getNamedType($type);
}
```

is found through the codebase many times to incorporate the dynamic syntax for field definition. This should be refactored to improve maintainability. :heart:

**Comment by rovansteen** [comment]
I think the best way to solve this would be to always work with an array. So in the 'public' API you can use both inline (`field => Type::string()`) as well as arrays (`field => ['type'=> Type::string()]`) but in Bakery we always convert to an array so we know what we are working with. I already wrote a utility function for this for the upcoming 1.0 release.
